/**
 * Template content registry — the single source both the `get_project_template` tool and
 * the `cleanroom://template/*` resource read from (structural byte-parity, DESIGN §7.2/§7.3).
 *
 * The 8 vendored modules are AUTO-GENERATED by scripts/vendor-template.ts; `checklist` is
 * hand-authored. This index is hand-authored and NOT regenerated.
 */

import buildGradle from './build-gradle.js';
import gradleProperties from './gradle-properties.js';
import settingsGradle from './settings-gradle.js';
import mcmodInfo from './mcmod-info.js';
import exampleModJava from './examplemod-java.js';
import mixinsJson from './mixins-json.js';
import modidAtCfg from './modid-at-cfg.js';
import readme from './readme.js';
import checklist from './checklist.js';

/** Frozen list of template components (matches BLIND_SPEC §0.2). */
export const TEMPLATE_COMPONENTS = [
  'build.gradle',
  'gradle.properties',
  'settings.gradle',
  'mcmod.info',
  'ExampleMod.java',
  'mixins.json',
  'modid_at.cfg',
  'README',
  'checklist',
] as const;

export type TemplateComponent = (typeof TEMPLATE_COMPONENTS)[number];

export const TEMPLATES: Record<TemplateComponent, string> = {
  'build.gradle': buildGradle,
  'gradle.properties': gradleProperties,
  'settings.gradle': settingsGradle,
  'mcmod.info': mcmodInfo,
  'ExampleMod.java': exampleModJava,
  'mixins.json': mixinsJson,
  'modid_at.cfg': modidAtCfg,
  README: readme,
  checklist,
};

export function getTemplate(component: string): string | undefined {
  return (TEMPLATES as Record<string, string>)[component];
}
